### ISSUE TITLE
Use Array.prototype.map instead of using for loop

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-angita1#1]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-angita1/blob/5de7cf05ab3a1513a24c4f084980e43881475034/index.js#L14-L16

**Comment by nishant-jain-94** [comment]
Array.prototype.map can be referred here from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by yaiphabee** [comment]
Use Array.prototype.map instead of for loop
